-- src/main/resources/db/migration/V1__init.sql

CREATE TABLE IF NOT EXISTS deck (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) UNIQUE NOT NULL,
  description VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS note (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deck_id BIGINT,
  front VARCHAR(1024) NOT NULL,
  back  VARCHAR(4096) NOT NULL,
  reading VARCHAR(256),
  pos VARCHAR(64),
  examples CLOB,
  synonyms VARCHAR(1024),
  antonyms VARCHAR(1024),
  mnemo VARCHAR(1024),
  tags VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY(deck_id) REFERENCES deck(id)
);

CREATE TABLE IF NOT EXISTS card (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id BIGINT NOT NULL,
  due_at TIMESTAMP,
  interval_days DOUBLE,
  ease DOUBLE DEFAULT 2.5,
  reps INT DEFAULT 0,
  lapses INT DEFAULT 0,
  status INT DEFAULT 0, -- 0 new,1 learning,2 review,3 suspended
  last_review_at TIMESTAMP,
  FOREIGN KEY(note_id) REFERENCES note(id)
);

CREATE TABLE IF NOT EXISTS review_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT,
  reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  rating INT,
  prev_interval DOUBLE,
  next_interval DOUBLE,
  ease DOUBLE,
  latency_ms INT,
  FOREIGN KEY(card_id) REFERENCES card(id)
);

CREATE INDEX IF NOT EXISTS idx_card_due ON card(due_at);
